account/urls.py
from django.urls import path, include
from .views import (
    register_view,
    login_view,
    logout_view,
    account_view,
    account_search_view,
    edit_account_view
)

app_name = 'account'

urlpatterns = [
    path('register', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('search/', account_search_view, name="search"),
    path('<user_id>/', account_view, name='profile'),
    path('<user_id>/edit/', edit_account_view, name='edit')
]

openChat/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('personal.urls')),
    path('account/', include('account.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

personal/urls.py
from django.urls import path
from .views import home

app_name = 'personal'

urlpatterns = [
    path('', home, name="home")
]

templates/snippets/footer.html
<style type="text/css">
  .footer {
    min-height: 100px;
  }
</style>

<!-- Footer -->

<div class="d-flex flex-row align-items-center footer bg-white shadow-lg mt-4">
  <p class="m-auto">Codingwithmitch Chat | 2020</p>
</div>
<!-- End Footer -->

templates/snippets/header.html
{% load static %}

<style type="text/css">
  .chat-dropdown-header:hover {
    cursor: pointer;
    background: var(--main-background-color);
  }
  .chat-dropdown-header {
    color: var(--light-primary-text-color);
  }
  .scrollable-menu {
    height: auto;
    max-height: 90vh;
    width: 500px;
    overflow-x: hidden;
  }

  .notifications-material-icon {
    font-size: 28px;
  }
  .notifications-icon-container {
    width: 40px;
    height: 40px;
    background-color: var(--main-background-color);
  }
  .notifications-icon-container:hover {
    cursor: pointer;
    background-color: var(--secondary-text-color);
  }
  .notify-badge {
    position: absolute;
    background: transparent;
    height: 1.2rem;
    width: 1.2rem;
    line-height: 1.2rem;
    top: 1rem;
    right: 2rem;
    text-align: center;
    font-size: 1rem;
    border-radius: 50%;
    color: white;
    font-weight: 630;
    margin-top: -15px;
    margin-right: -25px;
  }
  #id_notifications_spinner {
    margin-top: 20px;
    margin-bottom: 20px;
  }
</style>

<!-- Header -->
<div
  class="d-flex flex-column flex-lg-row p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm"
>
  <!-- MEDIUM+ SCREENS -->
  <div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-center">
    <h5 class="mr-3 font-weight-normal justify-content-start">
      <a class="p-2 text-dark" href="{% url 'personal:home' %}">Home</a>
    </h5>
    <form
      class="search-bar justify-content-start"
      onsubmit="return executeQuery();"
    >
      <input
        type="text"
        class="form-control"
        name="q"
        id="id_q_large"
        placeholder="Search..."
      />
    </form>

    <div class="d-flex flex-row-reverse flex-grow-1">
      <nav class="">
        {% if request.user.is_authenticated %}
        <div class="dropdown dropleft show p-2">
          <div class="d-flex flex-row">
            <div class="btn-group dropleft">
              <div
                class="d-flex notifications-icon-container rounded-circle align-items-center mr-3"
                id="id_chat_notification_dropdown_toggle"
                data-toggle="dropdown"
              >
                <span
                  id="id_chat_notifications_count"
                  class="notify-badge"
                ></span>
                <span
                  class="d-flex material-icons notifications-material-icon m-auto align-items-center"
                  >chat</span
                >
                <div
                  class="dropdown-menu scrollable-menu"
                  aria-labelledby="id_chat_notification_dropdown_toggle"
                  id="id_chat_notifications_container"
                ></div>
              </div>
            </div>

            <div class="btn-group dropleft">
              <div
                class="d-flex notifications-icon-container rounded-circle align-items-center mr-3"
                id="id_notification_dropdown_toggle"
                data-toggle="dropdown"
                onclick="setGeneralNotificationsAsRead()"
              >
                <span
                  id="id_general_notifications_count"
                  class="notify-badge"
                ></span>
                <span
                  class="d-flex material-icons notifications-material-icon m-auto align-items-center"
                  >notifications</span
                >
                <div
                  class="dropdown-menu scrollable-menu"
                  aria-labelledby="id_notification_dropdown_toggle"
                  id="id_general_notifications_container"
                ></div>
              </div>
            </div>

            <div class="btn-group dropleft">
              <img
                class="account-image rounded-circle m-auto d-block dropdown-toggle"
                id="id_profile_links"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                src="{{ request.user.profile_image.url }}"
                alt="codingwithmitch logo"
                width="40"
                height="40"
              />
              <div class="dropdown-menu" aria-labelledby="id_profile_links">
                <a
                  class="dropdown-item"
                  href="{% url 'account:profile' request.user.id %}"
                  >Account</a
                >
                <a class="dropdown-item" href="{% url 'account:logout' %}"
                  >Logout</a
                >
              </div>
            </div>
          </div>
        </div>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'account:login' %}">Login</a>
        <a class="btn btn-outline-primary" href="{% url 'account:register' %}"
          >Register</a
        >
        {% endif %}
      </nav>
    </div>
  </div>
  <!-- END MEDIUM+ SCREENS -->

  <!-- SMALL SCREENS -->
  <div class="d-flex d-md-none flex-column my-auto align-items-center">
    <h5 class="font-weight-normal">
      <a class="p-2 text-dark" href="#">Home</a>
    </h5>
    <form
      class="search-bar justify-content-start"
      onsubmit="return executeQuery();"
    >
      <input
        type="text"
        class="form-control"
        name="q"
        id="id_q_small"
        placeholder="Search..."
      />
    </form>
    <div class="d-flex flex-row-reverse flex-grow-1">
      <nav class="">
        {% if request.user.is_authenticated %}
        <div class="dropdown dropleft p-2 mt-2">
          <div class="d-flex flex-row">
            <div class="btn-group dropleft">
              <img
                class="account-image rounded-circle m-auto d-block dropdown-toggle"
                id="id_profile_links"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                src="{{ request.user.profile_image.url }}"
                alt="codingwithmitch logo"
                width="40"
                height="40"
              />
              <div class="dropdown-menu" aria-labelledby="id_profile_links">
                <a
                  class="dropdown-item"
                  href="{% url 'account:profile' request.user.id %}"
                  >Account</a
                >
                <a class="dropdown-item" href="{% url 'account:logout' %}"
                  >Logout</a
                >
              </div>
            </div>
          </div>
        </div>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'account:login' %}">Login</a>
        <a
          class="btn btn-outline-primary m-2"
          href="{% url 'account:register' %}"
          >Register</a
        >
        {% endif %}
      </nav>
    </div>
  </div>
  <!-- END SMALL SCREENS -->
</div>

<script type="text/javascript">
  function executeQuery() {
    var query = "";
    query = document.getElementById("id_q_small").value;
    if (query == "") {
      query = document.getElementById("id_q_large").value;
    }

    window.location.replace("{% url 'account:search' %}?q=" + query);
    return false;
  }
</script>

<!-- Setup SOCKET for NOTIFICATIONS -->